[package]
name = "foliage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", features = ["webgl"]}
winit = { version = "0.29.3", features = ["android-game-activity"]}
bevy_ecs = "0.11.0"
cfg-if = "1.0.0"
wasm-bindgen-futures = "0.4.38"
wasm-bindgen = "0.2.88"
web-sys = { version = "0.3.64", features = ["Window"] }
gloo-worker = { version = "0.5.0", features = ["futures"] }
serde = { version = "1.0.192", features = ["derive"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
nalgebra = "0.32.3"
anymap = "0.12.1"
compact_str = { version = "0.7.1" , features = ["serde"]}
rmp-serde = "1.1.2"
[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.3.0"