[package]
name = "foliage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", features = ["webgl"]}
winit = { version = "0.29.3", features = ["android-game-activity"]}
bevy_ecs = "0.12.0"
