[package]
name = "foliage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.19.0", default-features = false, features = ["webgl", "wgsl", "metal"]}
winit = { git = "https://github.com/rust-windowing/winit.git", features = ["android-game-activity", "x11"]}
#winit = { path = "../../winit-fork-29", features = ["android-game-activity", "x11"]}
bevy_ecs = "0.12.1"
cfg-if = "1.0.0"
wasm-bindgen-futures = "0.4.39"
wasm-bindgen = "0.2.89"
gloo-worker = { version = "0.5.0", features = ["futures"] }
serde = { version = "1.0.192", features = ["derive"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
nalgebra = "0.32.3"
anymap = "0.12.1"
compact_str = { version = "0.7.1" , features = ["serde"]}
rmp-serde = "1.1.2"
image = { version = "0.24.8" , features = ["png", "jpeg"]}
fontdue = "0.8.0"
indexmap = "2.1.0"
tracing = "0.1.40"
web-time = "1.0.0"
binpack2d = "1.0.1"
trait-variant = "0.1.1"
console_error_panic_hook = "0.1.7"
reqwest = { version = "0.11.23" , default-features = false, features = ["native-tls-vendored"]}
serde_json = "1.0.112"
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
derive_macros = { path = "../derive_macros"}
[target.'cfg(not(target_family = "wasm"))'.dependencies]
open = "5.0.1"
pollster = "0.3.0"
tokio = { version = "1.35.1", features = ["full"]}
copypasta = "0.10.0"
[dependencies.web-sys]
version = "0.3.67"
features = [
    "Window",
    "Performance",
    "Clipboard",
    "Navigator",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "WorkerGlobalScope",
]