[package]
name = "foliage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu.git", default-features = false, features = ["webgl", "wgsl"], rev = "552f06d"}
winit = { version = "0.29.8", features = ["android-game-activity", "x11"]}
bevy_ecs = "0.12.1"
cfg-if = "1.0.0"
wasm-bindgen-futures = "0.4.39"
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.67", features = ["Window", "Performance", "Clipboard", "Navigator"] }
gloo-worker = { version = "0.5.0", features = ["futures"] }
serde = { version = "1.0.192", features = ["derive"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
nalgebra = "0.32.3"
anymap = "0.12.1"
compact_str = { version = "0.7.1" , features = ["serde"]}
rmp-serde = "1.1.2"
image = { version = "0.24.6" , features = ["png", "jpeg"]}
fontdue = "0.8.0"
indexmap = "2.1.0"
tracing = "0.1.40"
web-time = "1.0.0"
binpack2d = "1.0.1"
trait-variant = "0.1.1"
console_error_panic_hook = "0.1.7"
[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.3.0"
tokio = { version = "1.35.1", features = ["full"]}
copypasta = "0.10.0"