[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true

[serve]
address = "192.168.1.183"
port = 8080
open = false
no_autoreload = true

[clean]
dist = "dist"
cargo = false

[tools]
wasm_bindgen = "0.2.92"
wasm_opt = "version_110"