[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/foliage"
filehash = true

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false
no_autoreload = true

[clean]
cargo = false

[tools]
wasm_bindgen = "0.2.100"
wasm_opt = "version_110"