[workspace]
members = [
    "foliage_proper",
    "application/example",
    "application/entry",
    "build_android",
    "website/entry",
    "website/system",
    "foliage_macros",
    "foliage_scenes",
    "foliage",
]
resolver = "2"

[profile.dev]
opt-level = 1