[workspace]
members = [
    "foliage",
    "application/example",
    "application/entry",
    "build_android",
    "website/entry",
    "website/system", "derive_macros",
]
resolver = "2"

[profile.dev]
opt-level = 1
