package = "entry"
arch = "x86_64-linux-android"
ndk_home = "/home/omi-voshuli/Desktop/dev/android_sdk/ndk/25.2.9519653"
sdk_home = "/home/omi-voshuli/Desktop/dev/android_sdk/"
min_sdk = 28
target_sdk = 31
compile_sdk = 31
android_application_version = "8.0.0"
gradle_distribution_url = "8.0-all"
ndk_version = "25.2.9519653"
androidx_version = "1.5.0"
androidx_constraintlayout_version = "2.0.4"
androidx_games_activity_version = "2.0.2"
androidx_fragment_version = "1.2.5"
oboe_version = "1.5.0"