[package]
name = "entry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
example = { path = "../example" }

[lib]
name = "entry_lib"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]