pub struct IconEntry {
    pub variant: String,
    /// File stem, e.g. `arrow-up` for `arrow-up.icon` sitting next to the generated file.
    pub file_stem: String,
}

pub struct CodegenConfig {
    pub enum_name: String,
    pub size: u32,
    pub mips: u32,
    /// Largest mip's pixel dimension (`size << (mips - 1)`).
    pub texture_scale: u32,
    pub dynamic: bool,
}

/// Emits the registration module: an `#[icon_handle]` enum (one variant per icon) plus a
/// `register(&mut Foliage)` function with one line per icon -- the codegen that replaces
/// hand-writing one enum variant + one `include_bytes!` + one `Icon::memory()` call per icon.
pub fn generate(entries: &[IconEntry], cfg: &CodegenConfig) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by foliage_icons -- do not edit by hand.\n");
    out.push_str(&format!(
        "// Regenerate via: foliage_icons gen --svg <svg-dir> --out <this-dir> --size {} --mips {}\n\n",
        cfg.size, cfg.mips
    ));
    out.push_str(
        "use foliage::{icon_handle, load_asset, EcsExtension, Foliage, Icon, IconId};\n\n",
    );
    out.push_str("#[icon_handle]\n");
    out.push_str(&format!("pub enum {} {{\n", cfg.enum_name));
    for e in entries {
        out.push_str(&format!("    {},\n", e.variant));
    }
    out.push_str("}\n\n");
    out.push_str(&format!(
        "pub const TEXTURE_SCALE: (f32, f32) = ({0:.1}, {0:.1});\n",
        cfg.texture_scale as f32
    ));
    out.push_str(&format!(
        "pub const RENDER_SIZE: (f32, f32) = ({0:.1}, {0:.1});\n",
        cfg.size as f32
    ));
    out.push_str(&format!("pub const MIP_COUNT: u32 = {};\n\n", cfg.mips));
    out.push_str("pub fn register(foliage: &mut Foliage) {\n");
    for e in entries {
        let id = format!("IconId::from({}::{})", cfg.enum_name, e.variant);
        if cfg.dynamic {
            out.push_str(&format!(
                "    let key = load_asset!(foliage, \"{stem}.icon\");\n",
                stem = e.file_stem
            ));
            out.push_str(&format!(
                "    foliage.world.spawn(Icon::memory_from_asset({id}, key, TEXTURE_SCALE.into(), RENDER_SIZE.into(), MIP_COUNT));\n"
            ));
        } else {
            out.push_str(&format!(
                "    foliage.world.spawn(Icon::memory_sized({id}, include_bytes!(\"{stem}.icon\"), TEXTURE_SCALE.into(), RENDER_SIZE.into(), MIP_COUNT));\n",
                stem = e.file_stem
            ));
        }
    }
    out.push_str("}\n");
    out
}
