pub struct IconEntry {
    pub variant: String,
    /// File stem, e.g. `arrow-up` for `arrow-up.icon` sitting next to the generated file.
    pub file_stem: String,
}

pub struct CodegenConfig {
    pub enum_name: String,
    /// Square MTSDF field resolution (texels per side).
    pub field_size: u32,
    /// Distance-field spread, in texels.
    pub px_range: f32,
}

/// Emits the registration module: an `#[icon_handle]` enum (one variant per icon) plus a
/// `register(&mut Foliage)` function with one line per icon. Each `.icon` payload is a raw
/// RGBA MTSDF field; icons are resolution-independent, so there is no per-size baking.
pub fn generate(entries: &[IconEntry], cfg: &CodegenConfig) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by foliage_icons -- do not edit by hand.\n");
    out.push_str(&format!(
        "// Regenerate via: foliage_icons gen --svg <svg-dir> --out <this-dir> --field-size {} --px-range {}\n\n",
        cfg.field_size, cfg.px_range
    ));
    out.push_str("use foliage::{icon_handle, Foliage, Icon, IconId};\n\n");
    out.push_str("#[icon_handle]\n");
    out.push_str(&format!("pub enum {} {{\n", cfg.enum_name));
    for e in entries {
        out.push_str(&format!("    {},\n", e.variant));
    }
    out.push_str("}\n\n");
    out.push_str(&format!(
        "pub const FIELD_SIZE: u32 = {};\n",
        cfg.field_size
    ));
    out.push_str(&format!(
        "pub const PX_RANGE: f32 = {:.1};\n\n",
        cfg.px_range
    ));
    out.push_str("pub fn register(foliage: &mut Foliage) {\n");
    for e in entries {
        let id = format!("IconId::from({}::{})", cfg.enum_name, e.variant);
        out.push_str(&format!(
            "    foliage.icon(Icon::msdf({id}, include_bytes!(\"{stem}.icon\"), FIELD_SIZE, PX_RANGE));\n",
            stem = e.file_stem
        ));
    }
    out.push_str("}\n");
    out
}
