[package]
name = "example"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foliage = {path = "../../foliage", features = ["scenes", "derive"] }
tracing = "0.1.40"
async-trait = "0.1.78"