[package]
name = "website_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foliage = { path = "../../foliage"}
foliage_scenes = { path = "../../foliage_scenes"}
tracing = "0.1.40"