//! The Rust module that registers a baked set.

use crate::msdf::Bake;
use crate::naming;

/// Emits the module that registers `stems` as a `Marks` set called `marks`.
///
/// A struct with one `Field` per mark, and the `Marks` impl that fills it. The fields are read
/// with `include_bytes!`, so the module belongs in the directory they were written to.
///
/// Every mark is reached by the name it was given rather than by an index, which is what lets a
/// set be regenerated after a mark is added or removed without moving a callsite.
///
/// # Errors
///
/// If `marks` does not reduce to a usable type name.
pub fn generate(stems: &[String], spec: Bake, marks: &str) -> Result<String, String> {
    let name = type_name(marks)?;
    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by foliage-icons -- do not edit by hand.\n");
    out.push_str(&format!(
        "// Regenerate with:\n\
         //     foliage-icons bake --svg <svg-dir> --out <this-dir> --marks {name} \\\n\
         //         --side {} --range {}\n\n",
        spec.side, spec.range
    ));

    out.push_str("use foliage::{Field, Grove, Marks};\n\n");
    out.push_str("/// How every field beside this module was baked.\n");
    out.push_str("///\n");
    out.push_str(
        "/// Both describe the bake rather than any one mark, which is why a set states them\n\
         /// once rather than per field.\n",
    );
    out.push_str(&format!("const SIDE: u32 = {};\n", spec.side));
    out.push_str(&format!("const RANGE: f32 = {:?};\n\n", spec.range));

    out.push_str(&format!("/// Every mark `{name}` holds.\n"));
    out.push_str(&format!("pub struct {name} {{\n"));
    for stem in stems {
        out.push_str(&format!("    /// The `{stem}` mark.\n"));
        out.push_str(&format!("    pub {}: Field,\n", naming::field(stem)));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl Marks for {name} {{\n"));
    out.push_str("    fn register(grove: &mut Grove) -> Self {\n");
    out.push_str("        Self {\n");
    for stem in stems {
        out.push_str(&format!(
            "            {}: grove.icon(include_bytes!(\"{stem}.icon\"), SIDE, RANGE),\n",
            naming::field(stem)
        ));
    }
    out.push_str("        }\n    }\n}\n");
    Ok(out)
}

/// `marks` as a `PascalCase` type name.
fn type_name(marks: &str) -> Result<String, String> {
    let name: String = naming::snake_case(marks)
        .split('_')
        .filter(|word| !word.is_empty())
        .map(|word| {
            let mut characters = word.chars();
            match characters.next() {
                Some(first) => first.to_uppercase().collect::<String>() + characters.as_str(),
                None => String::new(),
            }
        })
        .collect();
    match name.starts_with(|c: char| c.is_alphabetic()) {
        true => Ok(name),
        false => Err(format!("`{marks}` is not a usable type name")),
    }
}

#[cfg(test)]
mod tests {
    use super::{generate, type_name};
    use crate::msdf::Bake;

    fn stems() -> Vec<String> {
        vec!["arrow-up".to_string(), "check".to_string()]
    }

    #[test]
    fn a_set_name_is_taken_however_it_is_written() {
        assert_eq!(type_name("Icons").as_deref(), Ok("Icons"));
        assert_eq!(type_name("app_icons").as_deref(), Ok("AppIcons"));
        assert_eq!(type_name("app-icons").as_deref(), Ok("AppIcons"));
        assert!(type_name("2icons").is_err());
        assert!(type_name("--").is_err());
    }

    /// The generated module is what a dependent compiles, so every mark has to arrive as a
    /// documented field and as the line that registers it.
    #[test]
    fn every_mark_is_a_field_and_a_registration() {
        let generated = generate(&stems(), Bake::new(48, 3.0), "Icons").expect("generate");
        assert!(generated.contains("pub struct Icons {"));
        assert!(generated.contains("/// The `arrow-up` mark.\n    pub arrow_up: Field,"));
        assert!(generated.contains("pub check: Field,"));
        assert!(generated.contains("impl Marks for Icons {"));
        assert!(generated.contains(
            "arrow_up: grove.icon(include_bytes!(\"arrow-up.icon\"), SIDE, RANGE),"
        ));
        assert!(generated.contains("const SIDE: u32 = 48;"));
        assert!(generated.contains("const RANGE: f32 = 3.0;"));
    }

    /// A range that is not a whole number still has to emit as an `f32` literal rather than as
    /// an integer one, which would not compile.
    #[test]
    fn a_fractional_range_emits_as_a_float() {
        let generated = generate(&stems(), Bake::new(64, 2.5), "Icons").expect("generate");
        assert!(generated.contains("const RANGE: f32 = 2.5;"));
    }

    /// A mark named for a keyword is ordinary input, and the set has to compile with it in.
    #[test]
    fn a_keyword_mark_is_written_raw() {
        let stems = vec!["move".to_string()];
        let generated = generate(&stems, Bake::new(48, 3.0), "Icons").expect("generate");
        assert!(generated.contains("pub r#move: Field,"));
        assert!(generated.contains("r#move: grove.icon(include_bytes!(\"move.icon\")"));
    }
}
